# Generated by Django 4.0.3 on 2022-03-09 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='percent',
            field=models.IntegerField(null=True),
        ),
    ]
