# Generated by Django 4.0.3 on 2022-03-09 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_skills_percent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
